# Generated by Django 4.2.16 on 2024-09-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
