# Generated by Django 4.2.16 on 2024-09-19 15:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_bill_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
    ]
