# Generated by Django 4.2.16 on 2024-09-19 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_bill_discount_alter_bill_total_amount_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="date_generated",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
