# Generated by Django 4.2.16 on 2024-09-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_bill_date_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="date_generated",
            field=models.DateField(auto_now_add=True),
        ),
    ]
