# Generated by Django 4.2.16 on 2024-09-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grocery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stock_quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("consumption_per_day", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("menu", models.TextField()),
                ("cost_per_day", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
