# Generated by Django 4.2.16 on 2024-09-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grocery", "0001_initial"),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlanGrocery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "cost_for_grocery",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "grocery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grocery.grocery",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Grocery",
        ),
        migrations.RemoveField(
            model_name="mealplan",
            name="cost_per_day",
        ),
        migrations.AddField(
            model_name="mealplan",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplan",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default="lunch",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplangrocery",
            name="meal_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meals.mealplan"
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="groceries",
            field=models.ManyToManyField(
                through="meals.MealPlanGrocery", to="grocery.grocery"
            ),
        ),
    ]
