# Generated by Django 4.2.16 on 2024-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_mealplangrocery_delete_grocery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplangrocery",
            name="cost_for_grocery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
