# Generated by Django 4.2.16 on 2024-09-19 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="daily_meal_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
