# Generated by Django 4.2.16 on 2024-09-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_daily_meal_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
