# Generated by Django 4.2.16 on 2024-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("admin", "Admin"),
                    ("mess_staff", "Mess Staff"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
