# Generated by Django 4.2.16 on 2024-09-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_daily_meal_cost"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_leaves",
                to="accounts.student",
            ),
        ),
    ]
